<?php
/**
 * @category   Creativestyle
 * @package    Creativestyle_AffiliNet
 * @copyright  Copyright (c) 2014 creativestyle GmbH
 * @author     Marek Zabrowarny / creativestyle GmbH <support@creativestyle.de>
 */
?>
<script type="text/javascript">
    var type = 'AddToCart';
    var site = '<?php echo $this->getProgramId(); ?>';

    var product_id = '<?php echo $this->getProductId(); ?>';
    var product_price = '<?php echo $this->getProductPrice(); ?>';
<?php if ($this->getProductOldPrice()): ?>
    var product_oldprice = '<?php echo $this->getProductOldPrice(); ?>';
<?php endif; ?>
    var currency = '<?php echo $this->getCurrency(); ?>';
<?php if ($this->getProductQuantity()): ?>
    var product_quantity = '<?php echo $this->getProductQuantity(); ?>';
<?php endif; ?>
</script>
<script type="text/javascript" src="//<?php echo $this->getTrackingDomain(); ?>/art/JS/param.aspx"></script>
