<?php
/**
 * @category   Creativestyle
 * @package    Creativestyle_AffiliNet
 * @copyright  Copyright (c) 2014 creativestyle GmbH
 * @author     Marek Zabrowarny / creativestyle GmbH <support@creativestyle.de>
 */
?>
<script type="text/javascript">
    var type = 'Category';
    var site = '<?php echo $this->getProgramId(); ?>';

    var product_category = '<?php echo $this->getCategory(); ?>';
    var product_clickUrl = '<?php echo $this->getCategoryUrl(); ?>';
<?php if ($this->getCategoryImgUrl()): ?>
    var product_imgUrl = '<?php echo $this->getCategoryImgUrl(); ?>';
<?php endif; ?>
</script>
<script type="text/javascript" src="//<?php echo $this->getTrackingDomain(); ?>/art/JS/param.aspx"></script>
