<?php
/**
 * @category   Creativestyle
 * @package    Creativestyle_AffiliNet
 * @copyright  Copyright (c) 2014 creativestyle GmbH
 * @author     Marek Zabrowarny / creativestyle GmbH <support@creativestyle.de>
 */
?>
<script type="text/javascript">
    var type = 'CustomerData';
    var site = '<?php echo $this->getProgramId(); ?>';
</script>
<script type="text/javascript" src="//<?php echo $this->getTrackingDomain(); ?>/art/JS/param.aspx"></script>
