<?php
/**
 * @category   Creativestyle
 * @package    Creativestyle_AffiliNet
 * @copyright  Copyright (c) 2014 creativestyle GmbH
 * @author     Marek Zabrowarny / creativestyle GmbH <support@creativestyle.de>
 */
?>
<div class="content-header">
    <table cellspacing="0">
        <tr>
            <td style="<?php echo $this->getHeaderWidth() ?>"><?php echo $this->getHeaderHtml() ?></td>
            <td class="form-buttons"><?php echo $this->getButtonsHtml() ?></td>
        </tr>
    </table>
</div>
<div>
    <?php echo $this->getChildHtml('store_switcher') ?>
</div>
<div>
    <?php echo $this->getChildHtml('affilinet.statistics.filter.form') ?>
</div>
<div>
    <?php echo $this->getGridHtml() ?>
</div>
<script type="text/javascript">//<![CDATA[
    function filterFormSubmit() {
        var filters = $$('#filter_form input', '#filter_form select');
        var elements = [];
        for(var i in filters){
            if(filters[i].value && filters[i].value.length && !filters[i].disabled) elements.push(filters[i]);
        }
        var validator  = new Validation('filter_form');
        if (validator.validate()) {
            setLocation('<?php echo $this->getFilterUrl(); ?>filter/'+encode_base64(Form.serializeElements(elements))+'/');
        }
    }

    document.observe('dom:loaded', function() {
        new AffiliNet.StatisticsGrid('affilinetStatisticsGrid', {
            overview: '<?php echo $this->helper('affilinet')->__('Overview'); ?>',
            sales: '<?php echo $this->helper('affilinet')->__('Sales'); ?>',
            leads: '<?php echo $this->helper('affilinet')->__('Leads'); ?>',
            commission: '<?php echo $this->helper('affilinet')->__('Commission'); ?>',
            summary: '<?php echo $this->helper('affilinet')->__('Sum of commissions'); ?>'
        }, {
            gross: '<?php echo $this->helper('affilinet')->__('Gross'); ?>',
            net: '<?php echo $this->helper('affilinet')->__('Net'); ?>',
            open: '<?php echo $this->helper('affilinet')->__('Open'); ?>',
            cancelled: '<?php echo $this->helper('affilinet')->__('Cancelled'); ?>',
            confirmed: '<?php echo $this->helper('affilinet')->__('Confirmed'); ?>'
        });
    });

//]]></script>
