<?php
$id = $this->getRequest()->getParam('id', false);
if($id){
    echo $this->getFormInitScripts();
    ?>
    <script type="text/javascript">
        function openFeedPreview() {
            var url = '<?php echo $this->getUrl('*/*/preview/', array('id' => $id)) ?>?';
            if ($('browser_window') && typeof(Windows) != 'undefined') {
                Windows.focus('browser_window');
                return;
            }
            var dialogWindow = Dialog.info(null, {
                closable:true,
                resizable:false,
                draggable:true,
                className:'magento',
                windowClassName:'popup-window',
                title:'<?php echo Mage::helper('affilinet')->__('Preview'); ?>',
                top:50,
                width:1000,
                height:800,
                zIndex:1000,
                recenterAuto:false,
                hideEffect:Element.hide,
                showEffect:Element.show,
                id:'browser_window',
                url:url
            });
        }
    </script>
    <div class="content-header">
        <?php echo $this->getHeaderHtml(); ?>
        <p class="form-buttons"><?php echo $this->getButtonsHtml('header') ?></p>
    </div>
    <?php
    echo $this->getFormHtml();
    if ($this->hasFooterButtons()){
        ?>
        <div class="content-footer">
            <p class="form-buttons"><?php echo $this->getButtonsHtml('footer') ?></p>
        </div>
        <?php
    }
    echo $this->getFormScripts();
}
?>