<?php
/**
 * @category   Creativestyle
 * @package    Creativestyle_AffiliNet
 * @copyright  Copyright (c) 2014 creativestyle GmbH
 * @author     Marek Zabrowarny / creativestyle GmbH <support@creativestyle.de>
 */
?>
<div class="creativestyle-info">
    <a class="creativestyle-logo" href="http://www.creativestyle.de" target="_blank">
        <img src="<?php echo $this->getSkinUrl('creativestyle/images/affili-net-creativestyle-logo.png'); ?>" alt="creativestyle" />
    </a>
    <h3><?php echo $this->__('affilinet'); ?><small> (v. <?php echo $this->getExtensionVersion(); ?>)</small></h3>
    <p style="clear:both;"><?php echo $this->__('This extension integrates easily your Magento shop with affilinet services.'); ?></p>
    <p>--------------------------------------------------------<br />
        <?php echo $this->helper('affilinet')->__(
            'Visit <a href="%s" target="_blank">%s</a> to get more information.',
            $this->helper('affilinet')->__('http://www.creativestyle.net/services/magento.html'),
            $this->helper('affilinet')->__('http://www.creativestyle.net/services/magento.html'));
        ?>
    </p>
</div>
