<div class="content-header">
    <table cellspacing="0">
        <tbody>
            <tr>
                <td><h3 class="icon-head">affilinet Introduction</h3></td>
            </tr>
        </tbody>
    </table>
</div>
<div>
    <iframe id="affilinet-introduction-iframe" src="<?php echo $this->getIntroductionFrameSource(); ?>" style="width:100%;height:700px;" scrolling="auto" marginwidth="0" marginheight="0" frameborder="0" vspace="0" hspace="0"></iframe>
</div>